# Generated by Django 5.2.17 on 2026-09-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0016_seed_evidence_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="requeue_count",
            field=models.IntegerField(
                default=0,
                help_text="Veces que el reaper automático volvió a despachar este documento. Distinto de `retry_count` (reintentos pedidos por una persona).",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="status_changed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Momento del último cambio de `chunking_status`. Sin esto no se puede distinguir un documento recién encolado de uno trabado hace horas: `created_at` no sirve porque un reprocesamiento vuelve a PENDING un documento viejo.",
                null=True,
            ),
        ),
    ]
