# Generated by Django 5.2.17 on 2026-09-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0017_document_stuck_pending_recovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='evidence_tags',
            field=models.ManyToManyField(blank=True, help_text='Qué tipo de evidencia es este documento (NDC, NAP, salvaguardas…). Lo asigna quien lo carga, y toda operación que lo vincule lo hereda sin que nadie tenga que volver a marcarlo.', related_name='documents', to='document.evidencetag'),
        ),
    ]
