# Generated by Django 5.2.17 on 2026-09-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0018_evidence_tags_on_document'),
        ('project', '0010_backfill_project_document_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='tags_overridden',
            field=models.BooleanField(default=False, help_text='La operación decidió sus propias etiquetas para este documento. Mientras sea falso, el documento aporta las suyas (`Document.evidence_tags`) y un cambio en la biblioteca llega solo.'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Etiquetas propias de esta operación. Sólo cuentan con `tags_overridden`; si no, el vínculo usa las del documento.', related_name='project_documents', to='document.evidencetag'),
        ),
    ]
