# Generated by Django 5.2.17 on 2026-09-23 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_move_evidence_tags_to_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAlignmentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, max_length=40)),
                ('alineacion', models.JSONField(blank=True, default=dict)),
                ('monto', models.CharField(blank=True, max_length=80)),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('source', models.CharField(choices=[('edit', 'Edición'), ('backfill', 'Estado al activar el historial')], default='edit', max_length=20)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignment_snapshots', to='project.project')),
            ],
            options={
                'ordering': ('captured_at', 'id'),
                'indexes': [models.Index(fields=['project', 'captured_at'], name='project_pro_project_5782a4_idx')],
            },
        ),
    ]
