# Generated by Django 5.2.17 on 2026-08-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0022_definition_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillexecution',
            name='last_progress_at',
            field=models.DateTimeField(blank=True, help_text="Última vez que esta ejecución escribió un paso. Es lo único que permite distinguir 'sigue viva, tranquilo' de 'murió hace una hora' — antes de este campo esa pregunta no tenía respuesta en la base, y una ejecución podía quedar en running para siempre.", null=True),
        ),
        migrations.AlterField(
            model_name='skillexecution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('awaiting_approval', 'Awaiting Approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('stalled', 'Stalled')], default='pending', max_length=20),
        ),
    ]
