# Generated by Django 5.2.17 on 2026-09-17 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0025_map_iet_evidence_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skillexecution',
            name='promoted_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo alguien ascendió esta corrida a la que vale para el informe. La corrida vigente de una operación es la que tiene la fecha más nueva entre `finished_at` y `promoted_at`: por defecto gana la última que terminó, y ascender una vieja la pone adelante hasta que corra una nueva.', null=True),
        ),
        migrations.CreateModel(
            name='ExecutionSectionEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.PositiveIntegerField(help_text="`step_id` del paso dentro de `output_structured['steps']`. No es FK a SkillStep a propósito: la edición pertenece a lo que esta corrida escribió, y sigue siendo legible aunque el paso se borre de la definición.")),
                ('draft', models.TextField(blank=True, help_text='Markdown en curso. Vacío significa que no hay nada sin publicar para este paso.')),
                ('published', models.TextField(blank=True, help_text='Markdown que el informe muestra en lugar de la salida original. Vacío significa que el informe sigue mostrando lo que escribió el agente.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_edits', to='skill.skillexecution')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_execution_sections', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_section_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('step_id',),
            },
        ),
        migrations.CreateModel(
            name='ExecutionSectionEditVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_section_edit_versions', to=settings.AUTH_USER_MODEL)),
                ('edit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='skill.executionsectionedit')),
            ],
            options={
                'ordering': ('-version_number',),
            },
        ),
        migrations.AddIndex(
            model_name='executionsectionedit',
            index=models.Index(fields=['execution', 'step_id'], name='skill_execu_executi_a2d81f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='executionsectionedit',
            unique_together={('execution', 'step_id')},
        ),
        migrations.AlterUniqueTogether(
            name='executionsectioneditversion',
            unique_together={('edit', 'version_number')},
        ),
    ]
